disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Cristina Vera"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Cristina Vera"
image = "img/icon.png"
#   imageQuality = 96
headline = "Game developer who wants to make meaningful experiences with a passion for crafting gameplay that feels great."
subtitle = "I want to make meaningful experiences with a passion for crafting gameplay that feels great."
bio = ""
links = [
  { github = "https://github.com/cvg42" },
  { itch-io = "https://username.itch.io" },
  { linkedin = "https://linkedin.com/in/cristina-vera-g" },
  { spotify = "https://open.spotify.com/user/milchtein" },
]
